enum ErreurContextUtilisateur {
  ERREUR_UTILISATEUR_NON_CONNECTE = "ERREUR_UTILISATEUR_NON_CONNECTE",
  ERREUR_LIEU_FAV_NON_TROUVE = "ERREUR_LIEU_FAV_NON_TROUVE",
  ERREUR_USE_CONTEXT_HORS_PROVIDER = "ERREUR_USE_CONTEXT_HORS_PROVIDER"
}

export default ErreurContextUtilisateur;