enum EvenementEnum {
  PRECIPITATION = "PRECIPITATION",
  TEMPERATURE_EXTREME_BASSE = "TEMPERATURE_EXTREME_BASSE",
  TEMPERATURE_EXTREME_HAUTE = "TEMPERATURE_EXTREME_HAUTE",
  VENT_VIOLENT = "VENT_VIOLENT",
  VISIBILITE_REDUITE = "VISIBILITE_REDUITE"
}

export default EvenementEnum;