enum EvenementEnum {
  PRECIPITATION = "PRECIPITATION",
  TEMPERATURE_EXTREME = "TEMPERATURE_EXTREME",
  VENT_VIOLENT = "VENT_VIOLENT",
  VISIBILITE_REDUITE = "VISIBILITE_REDUITE"
}

export default EvenementEnum;