enum ErreurAuth {
  ERREUR_COMPTE_DESACTIVE = "ERREUR_COMPTE_DESACTIVE",
  ERREUR_IDENTIFIANTS_INVALIDES = "ERREUR_IDENTIFIANTS_INVALIDES",
  ERREUR_EMAIL_UTILISE = "ERREUR_EMAIL_UTILISE",
  ERREUR_EMAIL_INVALIDE = "ERREUR_EMAIL_INVALIDE",
  ERREUR_MDP_FAIBLE = "ERREUR_MDP_FAIBLE",
  ERREUR_RECONNEXION_NECESSAIRE = "ERREUR_RECONNEXION_NECESSAIRE",
  ERREUR_INCONNU = "ERREUR_INCONNU"
}

export default ErreurAuth;